export const SET_HEROES_SUCCESS = 'SET_HEROES_SUCCESS';
export const SET_HEROES_ERROR = 'SET_HEROES_ERROR';
export const SET_HEROES_LOADING = 'SET_HEROES_LOADING';
export const SET_SELECTED_HERO = 'SET_SELECTED_HERO';