export const FETCH_STORIES = 'FETCH_STORIES'
export const FETCH_STORIES_ID = 'FETCH_STORIES_ID'
export const FETCH_COMMENTS = 'FETCH_COMMENTS'
export const LOADING = 'LOADING'
export const LOADING_FINISH = 'LOADING_FINISH'
export const ERROR = 'ERROR'

