export const LOAD_TEAMS_SUCCESS = 'LOAD_TEAMS_SUCCESS';
export const LOAD_TEAMS_LOADING = 'LOAD_TEAMS_LOADING';
export const LOAD_TEAMS_ERROR = 'LOAD_TEAMS_ERROR';
export const LOAD_NEWTEAMS_SUCCESS = 'LOAD_NEWTEAMS_SUCCESS';
